### ISSUE TITLE
Add "analysis level" command line argument

### ISSUE THREAD

**Issue by chrisgorgo** [bids-apps/DPARSF#1]
All BIDS Apps implement the following compulsory command line options:

```app_name <input_folder> <output_folder> <analysis_level>```

Currently DPARSF is missing support for <analysis level>. Since right now it can only support participant level analyses it can just ignore the thirdpositional command line argument. It needs to be added for consistency across all BIDS Apps. The docker invocation would then look like this:

```docker run -i --rm -v /data/MyDataBIDS:/inputs:ro -v /data/DPARSFResults:/outputs dparsfdocker participant /inputs /outputs participant```

You can read more about how the role analysis level plays in parallelization [here](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005209#sec013).

**Comment by Chaogan-Yan** [comment]
Solved.
