### ISSUE TITLE
Add "--participant_label" command line argument

### ISSUE THREAD

**Issue by chrisgorgo** [bids-apps/DPARSF#2]
To allow BIDS Apps to parallelize over participants (remember that the input directory is the root of the dataset - not a single subject) each app need to support `--participant_label` command line argument. This optional argument has the following properties:

- When not included analysis should be done on all participants
- When included it should take a label of the participant you want to analyze. That label should not include the `sub-` prefix that is present in the folder names. For example `--participant_label 01`
- The argument can also take a space delimited list of labels. For example `--participant_label 01 03 10`.

More about command line arguments and parallelization can be found [here](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005209#sec013).

**Comment by Chaogan-Yan** [comment]
Solved.
