### ISSUE TITLE
CircleCI times-out while downloading from http://lab.rfmri.org/

### ISSUE THREAD

**Issue by chrisgorgo** [bids-apps/DPARSF#5]
There is a weird connectivity issue that prevents the tests to run correctly. Namely download of http://lab.rfmri.org/sites/default/files/DPABI/DPARSF/DPARSFA_run_StandAlone_Linux.zip times out. Each time you try to download it get a few first megabytes and then stalls. Furthermore it happens only on CircleCI servers (I can download it on my machine no problem) and other downloads do work without problems.

A workaround would be to put this archive on a different mirror - for example osf.io

**Comment by chrisgorgo** [comment]
This issue seems to have been resolved. https://circleci.com/gh/BIDS-Apps/DPARSF/13 Closing for now.

**Comment by chrisgorgo** [comment]
This seems to be happening again.

**Comment by Chaogan-Yan** [comment]
I guess this is because the server is in China.
I have uploaded the zip file to osf.
Please replace the path in Dockerfile to https://osf.io/e6qcr/?action=download and re-test it.
(I would like to preserve the original on master to make it work better in China.)
