### ISSUE TITLE
Add a --config command line option

### ISSUE THREAD

**Issue by chrisgorgo** [bids-apps/DPARSF#8]
This would allow users to pass their config .m files (http://rfmri.org/content/configurations-dparsfarun) without having to rebuild the container (which is not feasible in context of OpenNeuro).

**Comment by Chaogan-Yan** [comment]
Done

**Comment by chrisgorgo** [comment]
It seems you have implemented this by asking users to put the config files in the output directory. For this function to work on OpenNeuro we will need to DPARSF to accept path to a config file via `--config` command line argument (same as this is what SPM, C-PAC, FreeSurfer, FMRIPREP and other apps already handle input files - you can look up how they do it).

In addition, for the sake of provenance, it would make sense for DPARSF to copy the config file to the output directory.

**Comment by Chaogan-Yan** [comment]
Function '--config' added. Please try again.
